### ISSUE TITLE
Crash on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by peerstelter** [ElectronicTheatreControlsLabs/OSCRouter#1]
Hey,
the Download version of OSCRouter crash on my Mac System direct at the startup.
My System:
Mac Pro 2 x 2,4GHz Quad-Core Xeon
6 GB Ram
Mac OSX 10.8.5

any Ideas ?
Greetings Peer

**Comment by MizPlusPlus** [comment]
Hey Peer,

Oops, the crash was happening in a call to suppress AppNap, which did not exist in OSX 10.8.5 or earlier.  I just published a new release with the fix...

~Chris

**Comment by peerstelter** [comment]
You are awesome !
The fix work Perfect !
Thx
Peer

**Comment by MizPlusPlus** [comment]
:thumbsup:
